const { GoogleGenAI } = require("@google/genai")
const { z } = require("zod");
const { zodToJsonSchema } = require("zod-to-json-schema")
const puppeteer = require("puppeteer")

const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY
});

const interviewReportSchema = z.object({
    matchScore: z.number().describe("A score between 0 and 100 indicating how well the candidate's profile matches the job describe"),
    technicalQuestions: z.array(z.object({
        question: z.string().describe("the technical question can be asked in the interview"),
        intention: z.string().describe("the intention of interviewer behind asking this question "),
        answer: z.string().describe("How to answer this question, what points to cover,what approaches to take etc. "),
    })).describe("technical questions that can be asked in the interview along with their intention and how to answer them "),
    behavioralQuestions: z.array(z.object({
        question: z.string().describe("the technical question can be asked in the interview"),
        intention: z.string().describe("the intention of interviewer behind asking this question "),
        answer: z.string().describe("How to answer this question, what points to cover,what approaches to take etc. "),
    })).describe("behavioral questions that can be asked in the interview along with their intention and how to answer them "),
    skillGaps: z.array(z.object({
        skill: z.string().describe("the skill which the candidate is lacking"),
        severity: z.enum(["low", "medium", "high"]).describe("the severity of this skill gap, i.e. how important  it is for the candidate to improve this skill")
    })).describe("list of skill gaps in the candidates profile along with their severity "),
    preparationPlan: z.array(z.object({
        day: z.number().describe("the day number in the preparation plan , startig from 1 "),
        focus: z.string().describe("The main focus of this day in the preparation plan, e.g. data structures, system design, mock interviews etc."),
        tasks: z.array(z.string()).describe("List of tasks to be done on this day to follow the preparation plan, e.g. read a specific book or article, solve a set of problems, watch a video etc.")
    })).describe("A day-wise preparation plan for the candidate to follow in order to prepare for the interview effectively"),
    title: z.string().describe("the title of the job for which the interview report is generated ")
});


async function generateInterviewReport({ resume, selfDescription, jobDescription }) {

    const prompt = `generate an interview report for a candidate with the following details:
           Resume: ${resume}
           Self Description: ${selfDescription}
           Job Description: ${jobDescription}
           `

    const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseJsonSchema: zodToJsonSchema(interviewReportSchema)
        }
    })
    return JSON.parse(response.text);

}

async function generatePdfFromHtml(htmlContent) {
    const browser = await puppeteer.launch()
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil:"networkidle0"})

    const pdfBuffer = await page.pdf({ format: "A4",margin: { top: "20mm", bottom:"20mm", left: "15mm", right:"15mm"}})

    await browser.close()

    return pdfBuffer
}

async function generateResumePdf( resume, selfDescription, jobDescription){
   
    const resumePdfSchema = z.object({
        html: z.string().describe("The HTML content of the resume which can be converted to PDF using any library like puppeteer")
    })

    const prompt = `Generate a resume PDF for a candidate with the following details
                       Resume: ${resume}
                       Self Description: ${selfDescription}
                       Job Description: ${jobDescription}

                       the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to pdf using any library like puppeter
                        the resume should be tailored for the given job description and should highlight the candidates strength and relevant experience , the HTML content should be well formatted and structured , making it easy to read and visible 
                        the content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                       you can highlight the content using some colors or different font style but the overall design should be simple and professional .
                        `

    const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
        config:{
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(resumePdfSchema)
        }
    })

    const jsonContent =  JSON.parse(response.text)

    const pdfBuffer = await generatePdfFromHtml(jsonContent.html)

    return pdfBuffer
}
module.exports = {generateInterviewReport, generateResumePdf}